version: 0.0
os: linux
files:
  - source: .
    destination: /srv/api-server
hooks:
  AfterInstall:
    - location: scripts/reload-pm2.sh
      timeout: 300
      runas: ubuntu
  ValidateService:
    - location: scripts/validate-service.sh
      timeout: 300
permissions:
  - object: /srv/api-server
    pattern: "**"
    owner: ubuntu
    group: ubuntu
