version: 0.0
os: linux
files:
  - source: .
    destination: /srv/api-server
hooks:
  AfterInstall:
    - location: scripts/reload_pm2.sh
      timeout: 300
      runas: ubuntu
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
