name: CI/CD

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install npm dependencies
      run: npm install
    - name: Run tests
      run: npm run test

  staging-deploy:
    runs-on: ubuntu-latest
    needs: [test]
    if: github.ref == 'refs/heads/develop'
    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install npm dependencies
      run: npm install
    - name: AWS Deploy push
      uses: ItsKarma/aws-cli@v1.70.0
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}
        AWS_DEFAULT_REGION: "ap-northeast-2"
      with:
        args: >-
          deploy push
          --application-name jedal-api
          --description "This is a revision for the staging-api-server"
          --ignore-hidden-files
          --s3-location s3://jedal-be/staging-api-server.zip
          --source .
    - name: AWS Create Deploy
      uses: ItsKarma/aws-cli@v1.70.0
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}
        AWS_DEFAULT_REGION: "ap-northeast-2"
      with:
        args: >-
          deploy create-deployment
          --application-name jedal-api
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name staging
          --file-exists-behavior OVERWRITE
          --s3-location bucket=jedal-be,key=staging-api-server.zip,bundleType=zip

  production-deploy:
    runs-on: ubuntu-latest
    needs: [test]
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install npm dependencies
      run: npm install
    - name: AWS Deploy push
      uses: ItsKarma/aws-cli@v1.70.0
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: "ap-northeast-2"
      with:
        args: >-
          deploy push
          --application-name api-server
          --description "This is a revision for the api-server"
          --ignore-hidden-files
          --s3-location s3://jedal-be/production-api-server.zip
          --source .
    - name: AWS Create Deploy
      uses: ItsKarma/aws-cli@v1.70.0
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: "ap-northeast-2"
      with:
        args: >-
          deploy create-deployment
          --application-name api-server
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name production
          --file-exists-behavior OVERWRITE
          --s3-location bucket=jedal-be,key=production-api-server.zip,bundleType=zip
